### ISSUE TITLE
Converting Java files in a directory

### ISSUE THREAD

**Issue by desparza22** [hmc-alpaqa/metrinome#42]
**Describe the bug**
When running "convert <path_to_directory>", only the filename is passed from do_convert(...) in core/command.py to to_graph(...) in lang_to_cfg/java.py, so "javac <file_name> -d <directory_path>" in to_graph(...) incorrectly searches the user's current directory for the file instead of <path_to_directory>.

**To Reproduce**
1. Make a directory with Java files in src
2. Run the REPL
3. Execute "convert <path_to_directory>"

**Temporary fix**
In do_convert(...) in core/command.py, I concatenated the path with the filename to to_graph(...) in lang_to_cfg/java.py which fixes this issue, although I am not sure if it creates other issues.

**Screenshots**
Before:
<img width="548" alt="Screen Shot 2021-06-04 at 11 04 26 AM" src="https://user-images.githubusercontent.com/44206338/120823122-17482d00-c525-11eb-92c7-9d44163c2a05.png">

After:
<img width="1259" alt="Screen Shot 2021-06-04 at 11 04 59 AM" src="https://user-images.githubusercontent.com/44206338/120823191-2e871a80-c525-11eb-93ce-65360ab66dd2.png">

**Comment by desparza22** [comment]
I just converted another file in a directory and the entire path was passed to do_convert(...). I am not sure what I did differently between these two instances but it seems like the path is passed some of the time, meaning that re-appending the path does not work.

**Comment by JoshCordova** [comment]
Was this on the current version? The debug message "This is a directory" was changed to "{filepath} is a directory" 4 months ago, and that same commit aimed to fix this sort of issue.

**Comment by desparza22** [comment]
Yes, I'm sorry about that! I had opened up an older version without realizing it.
